### ISSUE TITLE
Headers spacing problem

### ISSUE THREAD

**Issue by spuljko** [Madelena/Metrology-for-Hass#50] opened 2023-01-03 23:36 UTC
When header is in multiple lines spacing is too big.
Here is example for HACS
![SmartSelect_20230104_002625_Home Assistant](https://user-images.githubusercontent.com/14004088/210458668-48d07e24-bdad-4aff-82d1-b400de4536f5.jpg)
And here is the same page with default theme
![SmartSelect_20230104_002802_Home Assistant](https://user-images.githubusercontent.com/14004088/210458777-10fb0fbf-e520-4a2a-811c-1423b94706fa.jpg)

**Comment by Madelena** [comment] 2023-01-04 00:28
This bug should be fixed in the pre-release v1.8: https://github.com/Madelena/Metrology-for-Hass/releases/tag/1.8

Duplicate of #49

**Closed by Madelena** 2023-01-04 00:28 UTC
