### ISSUE TITLE
HA Log Errors.

### ISSUE THREAD

**Issue by SirGoodenough** [Madelena/Metrology-for-Hass#39] opened 2022-08-08 16:30 UTC
This is cool and all but it's making a right mess of my HA logs on 2 systems.....

Logger: homeassistant.util.yaml.loader
Source: util/yaml/loader.py:155
First occurred: 11:16:28 AM (380 occurrences)
Last logged: 11:16:28 AM

YAML file /config/themes/metro/metro.yaml contains duplicate key "accent-color". Check lines 23 and 766
YAML file /config/themes/metro/metro.yaml contains duplicate key "rgb-accent-color". Check lines 24 and 767
YAML file /config/themes/metro/metro.yaml contains duplicate key "card-mod-theme". Check lines 348 and 769
YAML file /config/themes/metro/metro.yaml contains duplicate key "modes". Check lines 27 and 773
YAML file /config/themes/metro/metro.yaml contains duplicate key "card-mod-theme". Check lines 769 and 788

and on another HA system, this

2022-08-06 11:35:22.803 WARNING (SyncWorker_1) [homeassistant.util.yaml.loader] YAML file /config/themes/metro/metro.yaml contains duplicate key "primary-background-color". Check lines 31 and 314
2022-08-06 11:35:22.803 WARNING (SyncWorker_1) [homeassistant.util.yaml.loader] YAML file /config/themes/metro/metro.yaml contains duplicate key "rgb-primary-background-color". Check lines 32 and 315
2022-08-06 11:35:22.803 WARNING (SyncWorker_1) [homeassistant.util.yaml.loader] YAML file /config/themes/metro/metro.yaml contains duplicate key "secondary-background-color". Check lines 33 and 316
2022-08-06 11:35:22.803 WARNING (SyncWorker_1) [homeassistant.util.yaml.loader] YAML file /config/themes/metro/metro.yaml contains duplicate key "card-background-color". Check lines 34 and 317
2022-08-06 11:35:22.803 WARNING (SyncWorker_1) [homeassistant.util.yaml.loader] YAML file /config/themes/metro/metro.yaml contains duplicate key "rgb-card-background-color". Check lines 35 and 318
2022-08-06 11:35:22.803 WARNING (SyncWorker_1) [homeassistant.util.yaml.loader] YAML file /config/themes/metro/metro.yaml contains duplicate key "mdc-ripple-color". Check lines 36 and 320
2022-08-06 11:35:22.803 WARNING (SyncWorker_1) [homeassistant.util.yaml.loader] YAML file /config/themes/metro/metro.yaml contains duplicate key "rgb-mdc-ripple-color". Check lines 37 and 321
2022-08-06 11:35:22.803 WARNING (SyncWorker_1) [homeassistant.util.yaml.loader] YAML file /config/themes/metro/metro.yaml contains duplicate key "primary-text-color". Check lines 40 and 323
2022-08-06 11:35:22.803 WARNING (SyncWorker_1) [homeassistant.util.yaml.loader] YAML file /config/themes/metro/metro.yaml contains duplicate key "rgb-primary-text-color". Check lines 41 and 324
2022-08-06 11:35:22.803 WARNING (SyncWorker_1) [homeassistant.util.yaml.loader] YAML file /config/themes/metro/metro.yaml contains duplicate key "secondary-text-color". Check lines 42 and 325
2022-08-06 11:35:22.803 WARNING (SyncWorker_1) [homeassistant.util.yaml.loader] YAML file /config/themes/metro/metro.yaml contains duplicate key "disabled-text-color". Check lines 45 and 326
2022-08-06 11:35:22.803 WARNING (SyncWorker_1) [homeassistant.util.yaml.loader] YAML file /config/themes/metro/metro.yaml contains duplicate key "mdc-theme-surface". Check lines 49 and 328
2022-08-06 11:35:22.803 WARNING (SyncWorker_1) [homeassistant.util.yaml.loader] YAML file /config/themes/metro/metro.yaml contains duplicate key "rgb-mdc-theme-surface". Check lines 50 and 329
2022-08-06 11:35:22.803 WARNING (SyncWorker_1) [homeassistant.util.yaml.loader] YAML file /config/themes/metro/metro.yaml contains duplicate key "mdc-dialog-scrim-color". Check lines 51 and 330
2022-08-06 11:35:22.803 WARNING (SyncWorker_1) [homeassistant.util.yaml.loader] YAML file /config/themes/metro/metro.yaml contains duplicate

And about a thousand more...

**Comment by Madelena** [comment] 2022-08-09 04:24
It should be fixed in the latest release v1.6.2. Please let me know if there are still issues. Thanks!

(Duplicate of #35)

**Closed by Madelena** 2022-08-09 04:24 UTC
Labels: duplicate
